/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * FastAPI JWT Auth Boilerplate
 * FastAPI Boilerplate with JWT Authentication
 * OpenAPI spec version: 0.1.0
 */
import type { BodyUpdateWasteReportStreetAddress } from './bodyUpdateWasteReportStreetAddress';
import type { BodyUpdateWasteReportCity } from './bodyUpdateWasteReportCity';
import type { BodyUpdateWasteReportPostalCode } from './bodyUpdateWasteReportPostalCode';
import type { BodyUpdateWasteReportLatitude } from './bodyUpdateWasteReportLatitude';
import type { BodyUpdateWasteReportLongitude } from './bodyUpdateWasteReportLongitude';
import type { BodyUpdateWasteReportWasteType } from './bodyUpdateWasteReportWasteType';
import type { BodyUpdateWasteReportQuantityEstimate } from './bodyUpdateWasteReportQuantityEstimate';
import type { BodyUpdateWasteReportUrgencyLevel } from './bodyUpdateWasteReportUrgencyLevel';
import type { BodyUpdateWasteReportDescription } from './bodyUpdateWasteReportDescription';
import type { BodyUpdateWasteReportReporterName } from './bodyUpdateWasteReportReporterName';
import type { BodyUpdateWasteReportReporterPhone } from './bodyUpdateWasteReportReporterPhone';

export interface BodyUpdateWasteReport {
  street_address?: BodyUpdateWasteReportStreetAddress;
  city?: BodyUpdateWasteReportCity;
  postal_code?: BodyUpdateWasteReportPostalCode;
  latitude?: BodyUpdateWasteReportLatitude;
  longitude?: BodyUpdateWasteReportLongitude;
  waste_type?: BodyUpdateWasteReportWasteType;
  quantity_estimate?: BodyUpdateWasteReportQuantityEstimate;
  urgency_level?: BodyUpdateWasteReportUrgencyLevel;
  description?: BodyUpdateWasteReportDescription;
  reporter_name?: BodyUpdateWasteReportReporterName;
  reporter_phone?: BodyUpdateWasteReportReporterPhone;
  photos?: Blob[];
}
