/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * FastAPI JWT Auth Boilerplate
 * FastAPI Boilerplate with JWT Authentication
 * OpenAPI spec version: 0.1.0
 */
import type { BodyLoginGrantType } from './bodyLoginGrantType';
import type { BodyLoginClientId } from './bodyLoginClientId';
import type { BodyLoginClientSecret } from './bodyLoginClientSecret';

export interface BodyLogin {
  grant_type?: BodyLoginGrantType;
  username: string;
  password: string;
  scope?: string;
  client_id?: BodyLoginClientId;
  client_secret?: BodyLoginClientSecret;
}
