/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * FastAPI JWT Auth Boilerplate
 * FastAPI Boilerplate with JWT Authentication
 * OpenAPI spec version: 0.1.0
 */

export * from './bodyCreateWasteReport';
export * from './bodyCreateWasteReportDescription';
export * from './bodyCreateWasteReportLatitude';
export * from './bodyCreateWasteReportLongitude';
export * from './bodyCreateWasteReportReporterPhone';
export * from './bodyLogin';
export * from './bodyLoginClientId';
export * from './bodyLoginClientSecret';
export * from './bodyLoginGrantType';
export * from './bodyUpdateWasteReport';
export * from './bodyUpdateWasteReportCity';
export * from './bodyUpdateWasteReportDescription';
export * from './bodyUpdateWasteReportLatitude';
export * from './bodyUpdateWasteReportLongitude';
export * from './bodyUpdateWasteReportPostalCode';
export * from './bodyUpdateWasteReportQuantityEstimate';
export * from './bodyUpdateWasteReportReporterName';
export * from './bodyUpdateWasteReportReporterPhone';
export * from './bodyUpdateWasteReportStreetAddress';
export * from './bodyUpdateWasteReportUrgencyLevel';
export * from './bodyUpdateWasteReportWasteType';
export * from './changePasswordRequest';
export * from './getUsersParams';
export * from './getWasteReportsParams';
export * from './hTTPValidationError';
export * from './quantityEstimate';
export * from './reportStatus';
export * from './token';
export * from './urgencyLevel';
export * from './user';
export * from './userCreate';
export * from './userCreateIsActive';
export * from './userEmail';
export * from './userId';
export * from './userIsActive';
export * from './userUpdate';
export * from './userUpdateEmail';
export * from './userUpdateIsActive';
export * from './userUpdatePassword';
export * from './userUpdateUsername';
export * from './userUsername';
export * from './validationError';
export * from './validationErrorLocItem';
export * from './wastePhotoResponse';
export * from './wasteReport';
export * from './wasteReportCreate';
export * from './wasteReportCreateStatus';
export * from './wasteReportList';
export * from './wasteReportListItem';
export * from './wasteReportResponse';
export * from './wasteReportResponseAdminNotes';
export * from './wasteReportResponseDescription';
export * from './wasteReportResponseLatitude';
export * from './wasteReportResponseLongitude';
export * from './wasteReportResponseReporterPhone';
export * from './wasteReportStatus';
export * from './wasteReportStatusProperty';
export * from './wasteReportUpdate';
export * from './wasteReportUpdateLocation';
export * from './wasteReportUpdateQuantity';
export * from './wasteReportUpdateStatus';
export * from './wasteReportUpdateWasteType';
export * from './wasteType';
export * from './wasteTypeInfo';
export * from './wasteTypesResponse';