/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * FastAPI JWT Auth Boilerplate
 * FastAPI Boilerplate with JWT Authentication
 * OpenAPI spec version: 0.1.0
 */

export type QuantityEstimate = typeof QuantityEstimate[keyof typeof QuantityEstimate];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const QuantityEstimate = {
  small: 'small',
  medium: 'medium',
  large: 'large',
  very_large: 'very_large',
} as const;
