/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * FastAPI JWT Auth Boilerplate
 * FastAPI Boilerplate with JWT Authentication
 * OpenAPI spec version: 0.1.0
 */
import type { UserCreateIsActive } from './userCreateIsActive';

export interface UserCreate {
  email: string;
  username: string;
  is_active?: UserCreateIsActive;
  is_superuser?: boolean;
  password: string;
}
