/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * FastAPI JWT Auth Boilerplate
 * FastAPI Boilerplate with JWT Authentication
 * OpenAPI spec version: 0.1.0
 */
import type { UserUpdateEmail } from './userUpdateEmail';
import type { UserUpdateUsername } from './userUpdateUsername';
import type { UserUpdateIsActive } from './userUpdateIsActive';
import type { UserUpdatePassword } from './userUpdatePassword';

export interface UserUpdate {
  email?: UserUpdateEmail;
  username?: UserUpdateUsername;
  is_active?: UserUpdateIsActive;
  is_superuser?: boolean;
  password?: UserUpdatePassword;
}
