/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * FastAPI JWT Auth Boilerplate
 * FastAPI Boilerplate with JWT Authentication
 * OpenAPI spec version: 0.1.0
 */
import type { UserEmail } from './userEmail';
import type { UserUsername } from './userUsername';
import type { UserIsActive } from './userIsActive';
import type { UserId } from './userId';

export interface User {
  email?: UserEmail;
  username?: UserUsername;
  is_active?: UserIsActive;
  is_superuser?: boolean;
  id?: UserId;
}
