/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * FastAPI JWT Auth Boilerplate
 * FastAPI Boilerplate with JWT Authentication
 * OpenAPI spec version: 0.1.0
 */
import type { WasteReportResponseLatitude } from './wasteReportResponseLatitude';
import type { WasteReportResponseLongitude } from './wasteReportResponseLongitude';
import type { WasteType } from './wasteType';
import type { QuantityEstimate } from './quantityEstimate';
import type { UrgencyLevel } from './urgencyLevel';
import type { WasteReportResponseDescription } from './wasteReportResponseDescription';
import type { WasteReportResponseReporterPhone } from './wasteReportResponseReporterPhone';
import type { ReportStatus } from './reportStatus';
import type { WasteReportResponseAdminNotes } from './wasteReportResponseAdminNotes';
import type { WastePhotoResponse } from './wastePhotoResponse';

export interface WasteReportResponse {
  /** @maxLength 255 */
  street_address: string;
  /** @maxLength 100 */
  city: string;
  /** @maxLength 20 */
  postal_code: string;
  latitude?: WasteReportResponseLatitude;
  longitude?: WasteReportResponseLongitude;
  waste_type: WasteType;
  quantity_estimate: QuantityEstimate;
  urgency_level: UrgencyLevel;
  description?: WasteReportResponseDescription;
  /** @maxLength 100 */
  reporter_name: string;
  reporter_phone?: WasteReportResponseReporterPhone;
  id: number;
  user_id: number;
  status: ReportStatus;
  admin_notes?: WasteReportResponseAdminNotes;
  created_at: string;
  updated_at: string;
  photos?: WastePhotoResponse[];
}
