/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * FastAPI JWT Auth Boilerplate
 * FastAPI Boilerplate with JWT Authentication
 * OpenAPI spec version: 0.1.0
 */
import type { WasteReportUpdateLocation } from './wasteReportUpdateLocation';
import type { WasteReportUpdateWasteType } from './wasteReportUpdateWasteType';
import type { WasteReportUpdateQuantity } from './wasteReportUpdateQuantity';
import type { WasteReportUpdateStatus } from './wasteReportUpdateStatus';

export interface WasteReportUpdate {
  location?: WasteReportUpdateLocation;
  waste_type?: WasteReportUpdateWasteType;
  quantity?: WasteReportUpdateQuantity;
  status?: WasteReportUpdateStatus;
}
