/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * FastAPI JWT Auth Boilerplate
 * FastAPI Boilerplate with JWT Authentication
 * OpenAPI spec version: 0.1.0
 */

export type WasteReportStatus = typeof WasteReportStatus[keyof typeof WasteReportStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const WasteReportStatus = {
  pending: 'pending',
  processing: 'processing',
  completed: 'completed',
  rejected: 'rejected',
} as const;
