/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * FastAPI JWT Auth Boilerplate
 * FastAPI Boilerplate with JWT Authentication
 * OpenAPI spec version: 0.1.0
 */
import type { WasteReportCreateStatus } from './wasteReportCreateStatus';

export interface WasteReportCreate {
  location: string;
  waste_type: string;
  quantity: number;
  status?: WasteReportCreateStatus;
}
