/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * FastAPI JWT Auth Boilerplate
 * FastAPI Boilerplate with JWT Authentication
 * OpenAPI spec version: 0.1.0
 */
import type { WasteReportStatusProperty } from './wasteReportStatusProperty';

export interface WasteReport {
  location: string;
  waste_type: string;
  quantity: number;
  status?: WasteReportStatusProperty;
  id: number;
  user_id: number;
  date: string;
}
