/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * FastAPI JWT Auth Boilerplate
 * FastAPI Boilerplate with JWT Authentication
 * OpenAPI spec version: 0.1.0
 */

export interface WastePhotoResponse {
  /** @maxLength 500 */
  photo_url: string;
  id: number;
  waste_report_id: number;
  uploaded_at: string;
}
